services:
  freddie:
    build: .
    container_name: freddie-ai-recruiter
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_CREDENTIALS_PATH=/app/credentials.json
      - SHEET_ID=${SHEET_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}
      - GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}
      - GMAIL_REFRESH_TOKEN=${GMAIL_REFRESH_TOKEN}
      - PORT=3000
    volumes:
      - ./credentials.json:/app/credentials.json # Mount Google credentials
      - ./candidates.db:/app/candidates.db       # Persist SQLite DB
    restart: unless-stopped